### ISSUE TITLE
Errors with 3.2.1

### ISSUE THREAD

**Issue by CobraOI** [Joshj5hawk/JoshJ5Hawk-SuperAmmo#4]
not sure if you aware mate but there's a load of error messages  every time i try launching the server. this is a little of it but the list is absolutely massive.

ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4606)
(node:10584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.cmd (D:\SPT\obj\bundle.js:18939:59)
    at $01161890cd8fa11f$export$c24e73273208a9bb.waitFor (D:\SPT\obj\bundle.js:18542:43)
    at WinstonLogger.logWithColor (D:\SPT\obj\bundle.js:18941:31)
    at SuperAmmo.addToMagazine (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:359:24)
    at SuperAmmo.addAmmoToAllMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:313:34)
    at SuperAmmo.addToChambersMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:541:14)
    at SuperAmmo.postDBLoad (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:109:14)
    at PostDBModLoader.executeMods (D:\SPT\obj\bundle.js:13882:45)
    at PostDBModLoader.onLoad (D:\SPT\obj\bundle.js:13866:14)
    at App.load (D:\SPT\obj\bundle.js:18491:59)
(node:10584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4607)
(node:10584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.cmd (D:\SPT\obj\bundle.js:18939:59)
    at $01161890cd8fa11f$export$c24e73273208a9bb.waitFor (D:\SPT\obj\bundle.js:18542:43)
    at WinstonLogger.logWithColor (D:\SPT\obj\bundle.js:18941:31)
    at SuperAmmo.addToMagazine (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:360:24)
    at SuperAmmo.addAmmoToAllMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:313:34)
    at SuperAmmo.addToChambersMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:541:14)
    at SuperAmmo.postDBLoad (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:109:14)
    at PostDBModLoader.executeMods (D:\SPT\obj\bundle.js:13882:45)
    at PostDBModLoader.onLoad (D:\SPT\obj\bundle.js:13866:14)
    at App.load (D:\SPT\obj\bundle.js:18491:59)
(node:10584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4608)
(node:10584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.cmd (D:\SPT\obj\bundle.js:18939:59)
    at $01161890cd8fa11f$export$c24e73273208a9bb.waitFor (D:\SPT\obj\bundle.js:18542:43)
    at WinstonLogger.logWithColor (D:\SPT\obj\bundle.js:18941:31)
    at SuperAmmo.addToMagazine (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:359:24)
    at SuperAmmo.addAmmoToAllMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:313:34)
    at SuperAmmo.addToChambersMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:541:14)
    at SuperAmmo.postDBLoad (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:109:14)
    at PostDBModLoader.executeMods (D:\SPT\obj\bundle.js:13882:45)
    at PostDBModLoader.onLoad (D:\SPT\obj\bundle.js:13866:14)
    at App.load (D:\SPT\obj\bundle.js:18491:59)
(node:10584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4609)
(node:10584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.cmd (D:\SPT\obj\bundle.js:18939:59)
    at $01161890cd8fa11f$export$c24e73273208a9bb.waitFor (D:\SPT\obj\bundle.js:18542:43)
    at WinstonLogger.logWithColor (D:\SPT\obj\bundle.js:18941:31)
    at SuperAmmo.addToMagazine (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:360:24)
    at SuperAmmo.addAmmoToAllMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:313:34)
    at SuperAmmo.addToChambersMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:541:14)
    at SuperAmmo.postDBLoad (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:109:14)
    at PostDBModLoader.executeMods (D:\SPT\obj\bundle.js:13882:45)
    at PostDBModLoader.onLoad (D:\SPT\obj\bundle.js:13866:14)
    at App.load (D:\SPT\obj\bundle.js:18491:59)
(node:10584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4610)
(node:10584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.cmd (D:\SPT\obj\bundle.js:18939:59)
    at $01161890cd8fa11f$export$c24e73273208a9bb.waitFor (D:\SPT\obj\bundle.js:18542:43)
    at WinstonLogger.logWithColor (D:\SPT\obj\bundle.js:18941:31)
    at SuperAmmo.addToMagazine (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:359:24)
    at SuperAmmo.addAmmoToAllMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:313:34)
    at SuperAmmo.addToChambersMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:541:14)
    at SuperAmmo.postDBLoad (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:109:14)
    at PostDBModLoader.executeMods (D:\SPT\obj\bundle.js:13882:45)
    at PostDBModLoader.onLoad (D:\SPT\obj\bundle.js:13866:14)
    at App.load (D:\SPT\obj\bundle.js:18491:59)
(node:10584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4611)
(node:10584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.cmd (D:\SPT\obj\bundle.js:18939:59)
    at $01161890cd8fa11f$export$c24e73273208a9bb.waitFor (D:\SPT\obj\bundle.js:18542:43)
    at WinstonLogger.logWithColor (D:\SPT\obj\bundle.js:18941:31)
    at SuperAmmo.addToMagazine (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:360:24)
    at SuperAmmo.addAmmoToAllMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:313:34)
    at SuperAmmo.addToChambersMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:541:14)
    at SuperAmmo.postDBLoad (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:109:14)
    at PostDBModLoader.executeMods (D:\SPT\obj\bundle.js:13882:45)
    at PostDBModLoader.onLoad (D:\SPT\obj\bundle.js:13866:14)
    at App.load (D:\SPT\obj\bundle.js:18491:59)
(node:10584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4612)
(node:10584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.cmd (D:\SPT\obj\bundle.js:18939:59)
    at $01161890cd8fa11f$export$c24e73273208a9bb.waitFor (D:\SPT\obj\bundle.js:18542:43)
    at WinstonLogger.logWithColor (D:\SPT\obj\bundle.js:18941:31)
    at SuperAmmo.addToMagazine (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:359:24)
    at SuperAmmo.addAmmoToAllMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:313:34)
    at SuperAmmo.addToChambersMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:541:14)
    at SuperAmmo.postDBLoad (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:109:14)
    at PostDBModLoader.executeMods (D:\SPT\obj\bundle.js:13882:45)
    at PostDBModLoader.onLoad (D:\SPT\obj\bundle.js:13866:14)
    at App.load (D:\SPT\obj\bundle.js:18491:59)
(node:10584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4613)
(node:10584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.cmd (D:\SPT\obj\bundle.js:18939:59)
    at $01161890cd8fa11f$export$c24e73273208a9bb.waitFor (D:\SPT\obj\bundle.js:18542:43)
    at WinstonLogger.logWithColor (D:\SPT\obj\bundle.js:18941:31)
    at SuperAmmo.addToMagazine (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:360:24)
    at SuperAmmo.addAmmoToAllMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:313:34)
    at SuperAmmo.addToChambersMags (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:541:14)
    at SuperAmmo.postDBLoad (D:\SPT\user\mods\JoshJ5Hawk-SuperAmmo\src\superammo.js:109:14)
    at PostDBModLoader.executeMods (D:\SPT\obj\bundle.js:13882:45)
    at PostDBModLoader.onLoad (D:\SPT\obj\bundle.js:13866:14)
    at App.load (D:\SPT\obj\bundle.js:18491:59)

**Comment by Joshj5hawk** [comment]
Sorry for the delay! Been out of town for a bit. Pushing the update now!
